apiVersion: apps/v1
kind: Deployment
metadata:
  name: iot-simulator
spec:
  replicas: 2
  selector:
    matchLabels:
      app: iot-simulator
  template:
    metadata:
      labels:
        app: iot-simulator
    spec:
      containers:
      - name: iot-simulator
        image: yourRegistryName.azurecr.io/iot-simulator:latest #check your registry name
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: iot-simulator-service
spec:
  type: ClusterIP
  selector:
    app: iot-simulator
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
